dist: trusty
sudo: false
language: php
notifications:
  email:
    on_success: never
    on_failure: change
branches:
  only:
  - master
  - develop
  - "/\\d+\\.\\d+\\.\\d+?.*/"
php:
- 7.2
- 7.3
env:
  global:
  - GIT_COMMITTER_NAME=travis-ci
  - GIT_COMMITTER_EMAIL=inc@2inc.org
  - GIT_AUTHOR_NAME=travis-ci
  - GIT_AUTHOR_EMAIL=inc@2inc.org
  - WP_VERSION=latest WP_MULTISITE=0
cache:
  directories:
  - node_modules
  - vendor
  - "$HOME/.composer/cache"
install:
- nvm install 12
- npm install
- npm rebuild node-sass
- composer install
before_script:
- bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
script:
- composer test
before_deploy:
- npm run build
- npm run zip
- ls -la snow-monkey-heading-widget-area.zip
- export RELEASE_FILE=$(ls snow-monkey-heading-widget-area.zip)
deploy:
  provider: releases
  api_key:
    secure: CORDE72TzqGnoKrSWGkNZO43wwnVDQp4VcBcg9b18S2IQRL4pWdjOKdWfiVEcWIY9ynOcDZX9UIBxYdGumf2KS8TKTVM7POz6Ip/pNrqOMFPOZMjHznugx+GWY3nNKj6rO90XrqG61Qky7XKcfietzchQbEieuaxKZHyw52OsJiVrfZcsYksn8s5oo1R0PJA0N0xauvtbHezd/4Hq1InCBlLmhI73TLrKp3Bo3hi9ZdlWRHM31iiG85nh4pZhc1hxwyIOBZnWSuLRgXpQCk+Ci2leIXQT62Wmit/ZEb5w8NRU7gRu7XbSbDoMHSKeVOaq9xZbKgIgNTXOtSYWmQNPsJudlUKAJ9mNHgZ2+rFuN/gZ6ED8da7egR6VSrJLyrRFTVKjM6DbEURESxXLpQ1ZdoHldu7U9dC1oR/SMbCEpAJ9jsfJ9FLbCa5zXQCM6pY5cEBs6Vd3/YJ+kjtORsNZronD0jaGk3OnQ/SQotligqfDMSgFf8sHeMjOwsOJ7POdaH9b2vAmGbwO7CtG44Klx1bQvAloA8WFL+bbViopVvCgS2w66RhcPKhy0utqvOK4h/cYCY8bE8feW9AdWe0LUGCmBIBFnJ3KHIelJFCMnygVKPG3bwnhSHTEwt6Nevx6KryyDJUoyYgS45AMk1fSPT/MUy7l0QB6QwyrYBW46o=
  file: "${RELEASE_FILE}"
  skip_cleanup: true
  on:
    tags: true
    php: 7.3
    repo: inc2734/snow-monkey-heading-widget-area
