sudo: false
language: php
notifications:
  email:
    on_success: never
    on_failure: change
branches:
  only:
  - master
  - develop
  - "/\\d+\\.\\d+\\.\\d+?.*/"
php:
- 5.6
- 7.1
env:
  global:
  - GIT_COMMITTER_NAME=travis-ci
  - GIT_COMMITTER_EMAIL=inc@2inc.org
  - GIT_AUTHOR_NAME=travis-ci
  - GIT_AUTHOR_EMAIL=inc@2inc.org
  - WP_VERSION=latest WP_MULTISITE=0
cache:
  directories:
  - node_modules
  - vendor
  - "$HOME/.composer/cache"
install:
- nvm install 8
- npm install
- composer install
before_script:
- bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
script:
- composer test
- npm run lint
before_deploy:
- npm run zip
- ls -la snow-monkey-heading-widget-area.zip
- export RELEASE_FILE=$(ls snow-monkey-heading-widget-area.zip)
deploy:
  provider: releases
  api_key:
    secure: GGHD/Gd7bQmQ4vkGNtVS6OE+nfBq7DxyPEm9x748KvrZEKixWmoooZacyEmjgkeQyjklzchj3+z4S+VTcuG0XeczUDDDE9lSujVqLFh8PIHtL0W2by5a0sbHH6ypBXt1/E/5OHyjz9G4C/eVdRyC9pi/207EATkRmZEK1HMYNVzefw1R7wnmib++TBF/orja4Mo0WY/3llnGg+0BQubFAm9totmWQrgLaztYvjBRSQjgdbX3hbkD33tXmq6xXNgL3o9henX6+o1bVa6wnaD1K1kVxP7VUEAvIDBV0f/tCUSMLZah8wHKT4TD7Q2UfrfMRtbNKoq/ZPzKtv9asXEuQIUz7FZl50ZU7x8CgxjqXvb0DHu7ow7JxtLHVNbMQezEtty96stCJwRi70spXZGJalOkp8d1SABlbFGWTfQTg3u3mOYvysQN16xnQAZtEr+gIKc28Zs8gNQ1/OaSg1us7qJ1Jtdh2tEdeFnlEVuKtytYcrdjHm7bsN/Sk/b+C5dO32qAIitQFMa8tepLqBxxlpkzVCjHAqB5DDLHHMHDynU3aVOBxLVEmQpnrxu6XXIAQmIOtav/shGdzgb/c24UalNq9kEmOzZNyuTUgrlft19HUnTi1FCsfHLOAUT5zjmL1Lm6HRxzBRxY7NA6R5ek0a8LfkLpxLrXN2eXZIKwrS4=
  file: "${RELEASE_FILE}"
  skip_cleanup: true
  on:
    tags: true
    php: 7.1
    repo: inc2734/snow-monkey-blocks
